[project]
name = "video_frame_viewer"
version = "1.0.0"
requires-python = ">= 3.8"
dependencies = [
    "numpy",
    "opencv-python",
    "pillow",
    "fire",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
exclude = [""]
[project.scripts]
frame-save = "frame_viewer.cli:app"